[client]
http_request = """
POST / HTTP/1.0
Host: fronted-domain.com
Content-Length: 99999999999999999
X-2ra-version: <VER>
"""
buffer_size = 1024
tx_sni = "tx.com"
rx_sni = "rx.com"
insecure_tls = true
# socks5 addr
inbound_addr = "127.0.0.1:5123"
# 2ra server addr
outbound_addr = "127.0.0.1:443"
separator = ["\r", "\n", "\r", "\n"]
udp_bind_addr = "127.0.0.16:0"

[server-disable]
http_response = """
HTTP/1.0 200 OK
Content-Type: text/html; charset=UTF-8
Server: gws
"""
buffer_size = 1024
inbound_addr = "127.0.0.1:4433"
cert_pem_path = "./cert/cert.pem"
key_pem_path = "./cert/key.pem"
separator = ["\r", "\n", "\r", "\n"]
udp_bind_addr = "127.0.0.17:0"