[client]
http_request = """
POST / HTTP/1.0
Host: example.org
X-2ra-version: <VER>
"""
buffer_size = 1024
tx_sni = "site1.com"
rx_sni = "site.com"
insecure_tls = true
# socks5 addr
inbound_addr = "127.0.0.1:5123"
# 2ra server addr
outbound_addr = "127.0.0.1:4433"
separator = ["\r", "\n", "\r", "\n"]

[server]
http_response = """
HTTP/1.1 200 OK
X-2ra-version: <VER>
"""
buffer_size = 1024
inbound_addr = "127.0.0.1:4433"
cert_pem_path = "./cert/cert.pem"
key_pem_path = "./cert/key.pem"
separator = ["\r", "\n", "\r", "\n"]